import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <head>
        <title>Ramez Al-Siddiq Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel='icon' href="/favicon.ico" />
      </head>

      <main>
        <section className='min-h-screen'>
          <nav></nav>
          <h1>Ramez Al-Siddiq</h1>
        </section>
      </main>
    </div>
  );
}